config:
  toggl_token: xxxxx #toggl api token
  toggl_ws_id: 12345 #toggle workspace id
  pt_token: xxxxxxx #Pivotal Tracker api token
  gh_un: geoffcheeseman #github username
  gh_pw: ilovecheese #github password
  gh_org: chedderltd #github organisation
  dropbox_folder: mydropbox #path to local informatics dropbox folder